# Generated by Django 5.0.2 on 2024-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpStudent', '0003_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
